// Runs after `docusaurus gen-api-docs`. The generated docs/reference/ folder is
// picked up by the autogenerated sidebar; this writes the category label/position
// (gen-api-docs doesn't emit a _category_.json) so it slots between API (20) and
// Legal (50). Method badges come from each page's `sidebar_class_name`.
import {writeFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {dirname, resolve} from 'node:path';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = resolve(root, 'docs/reference/_category_.json');

const category = {
  label: 'Справочник API',
  position: 30,
  collapsed: false,
};

writeFileSync(OUT, JSON.stringify(category, null, 2) + '\n');
console.log(`[postgen-openapi] wrote ${OUT}`);
