// Runs after `docusaurus gen-api-docs`. The generated docs/reference/ folder is
// picked up by the autogenerated sidebar; this writes the category label/position
// (gen-api-docs doesn't emit a _category_.json) so it slots between API (20) and
// Legal (50). Method badges come from each page's `sidebar_class_name`.
import {mkdirSync, writeFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import {dirname, resolve} from 'node:path';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
// Одна категория на локаль: ru лежит в docs/, en — в i18n/en/.
const TARGETS = [
  {out: resolve(root, 'docs/reference/_category_.json'), label: 'Справочник API'},
  {
    out: resolve(
      root,
      'i18n/en/docusaurus-plugin-content-docs/current/reference/_category_.json',
    ),
    label: 'API reference',
  },
];

for (const {out, label} of TARGETS) {
  mkdirSync(dirname(out), {recursive: true});
  writeFileSync(out, JSON.stringify({label, position: 30, collapsed: false}, null, 2) + '\n');
  console.log(`[postgen-openapi] wrote ${out}`);
}
